// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNAF-eCQ8WM2_F6iMRHnJp010IQOAN9M',
    appId: '1:1043023315503:web:b087eb9b013ab212207cda',
    messagingSenderId: '1043023315503',
    projectId: 'flutter-ideaink-project',
    authDomain: 'flutter-ideaink-project.firebaseapp.com',
    storageBucket: 'flutter-ideaink-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVpM2vHVqoxDI2LJTeXBeFHRww_zKsd4',
    appId: '1:1043023315503:android:ab1815f10725b133207cda',
    messagingSenderId: '1043023315503',
    projectId: 'flutter-ideaink-project',
    storageBucket: 'flutter-ideaink-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFqQ7oINk5psIQBz1ok5jbcEtnKEi4ag',
    appId: '1:1043023315503:ios:8b068f8ce1239602207cda',
    messagingSenderId: '1043023315503',
    projectId: 'flutter-ideaink-project',
    storageBucket: 'flutter-ideaink-project.appspot.com',
    iosBundleId: 'com.indiagrow.idea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNFqQ7oINk5psIQBz1ok5jbcEtnKEi4ag',
    appId: '1:1043023315503:ios:8b068f8ce1239602207cda',
    messagingSenderId: '1043023315503',
    projectId: 'flutter-ideaink-project',
    storageBucket: 'flutter-ideaink-project.appspot.com',
    iosBundleId: 'com.indiagrow.idea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNAF-eCQ8WM2_F6iMRHnJp010IQOAN9M',
    appId: '1:1043023315503:web:6281eb46a33c7fd3207cda',
    messagingSenderId: '1043023315503',
    projectId: 'flutter-ideaink-project',
    authDomain: 'flutter-ideaink-project.firebaseapp.com',
    storageBucket: 'flutter-ideaink-project.appspot.com',
  );
}
